// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoOjl3RuUosHhYLKQhQp5kTs-8dQ_Etfo',
    appId: '1:819560064723:web:607b1781fde2f74c211626',
    messagingSenderId: '819560064723',
    projectId: 'ngo-app-3ccdf',
    authDomain: 'ngo-app-3ccdf.firebaseapp.com',
    storageBucket: 'ngo-app-3ccdf.appspot.com',
    measurementId: 'G-WEDHQW4J9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4zspBVyVfN4w5iswhjRs82H8J15p_6w8',
    appId: '1:819560064723:android:3c2c712753c4aaf0211626',
    messagingSenderId: '819560064723',
    projectId: 'ngo-app-3ccdf',
    storageBucket: 'ngo-app-3ccdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxgWZRjbBuYRvnWCV_JZAfWWLeAEx6NbQ',
    appId: '1:819560064723:ios:9359d047d1e8623d211626',
    messagingSenderId: '819560064723',
    projectId: 'ngo-app-3ccdf',
    storageBucket: 'ngo-app-3ccdf.appspot.com',
    iosBundleId: 'com.ovibo.ngo.ngoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxgWZRjbBuYRvnWCV_JZAfWWLeAEx6NbQ',
    appId: '1:819560064723:ios:9359d047d1e8623d211626',
    messagingSenderId: '819560064723',
    projectId: 'ngo-app-3ccdf',
    storageBucket: 'ngo-app-3ccdf.appspot.com',
    iosBundleId: 'com.ovibo.ngo.ngoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoOjl3RuUosHhYLKQhQp5kTs-8dQ_Etfo',
    appId: '1:819560064723:web:a6d4c343f415b271211626',
    messagingSenderId: '819560064723',
    projectId: 'ngo-app-3ccdf',
    authDomain: 'ngo-app-3ccdf.firebaseapp.com',
    storageBucket: 'ngo-app-3ccdf.appspot.com',
    measurementId: 'G-BLF0D8JXEM',
  );
}
